const userActions = {
  SIGN_IN: "SIGN_IN",
  SIGN_IN_GOOGLE: "SIGN_IN_GOOGLE",
  SIGN_IN_FACEBOOK: "SIGN_IN_FACEBOOK",
  SIGN_IN_TWITTER: "SIGN_IN_TWITTER",
  SIGN_OUT: "SIGN_OUT",
  SIGN_UP: "SIGN_UP",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  RETRIEVE_TOKEN: "RETRIEVE_TOKEN"
};

export default userActions;